apiVersion: v1
kind: Namespace
metadata:
  name: wa
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-app
  namespace: wa
  labels:
    app: cards

spec:
  replicas: 2
  selector:
    matchLabels:
      app: cards

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: cards

    spec:
      containers:
        - name: cards-server
          image: chimenesjr/solitaire:nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          envFrom:
---

apiVersion: v1
kind: Service
metadata:
  name: cards-srv
  namespace: wa
spec:
  type: NodePort
  selector:
    app: cards
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
