apiVersion: v1
kind: Namespace
metadata:
  name: wa
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: wa
  labels:
    app: weatherapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: weather

    spec:
      containers:
        - name: app-server
          image: "doronamsalem/website:webserver"
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          envFrom:
            - configMapRef:
                name: yellow
---

apiVersion: v1
kind: Service
metadata:
  name: weatherapp-srv
  namespace: wa
spec:
  type: NodePort
  selector:
    app: weather
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8081
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: yellow
  namespace: wa
data:
  BG_COLOR: "#FAFAD2"
