apiVersion: v1
kind: Namespace
metadata:
  name: staging
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: staging
  labels:
    app: weatherapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather

  template:
    metadata:
      labels:
        app: weather

    spec:
      containers:
      - name: app-server
        image: "test_image:version"
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
          - configMapRef:
              name: yellow    
---

apiVersion: v1
kind: Service
metadata:
  name: test-weatherapp-srv
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: weather
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: yellow
  namespace: staging
data:
  BG_COLOR: "#FAFAD2"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: blue
  namespace: staging
data:
  BG_COLOR: "#87CEFA"
