apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/doronamsalem/configuration.git
    path: helm-production
    targetRevision: HEAD
  
  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
